### ISSUE TITLE
Error: initialization error of test in flaky-test filter

### ISSUE THREAD

**Issue by wahleric** [randoop/randoop#425] opened 2019-02-04 06:02 UTC
1. Randoop version: 4.1.0
2. Command run: java -ea -Xmx3000m -classpath repo.jar:randoop-all-4.1.0.jar:junit.jar randoop.main.Main gentests --testclass=junit.framework.Assert --output-limit=200 --flaky-test-behavior=DISCARD
3. Output:
PUBLIC MEMBERS=40
Explorer = randoop.generation.ForwardGenerator(allSequences.size()=0,observers.size()=0,subsumed_sequences.size()=0,runtimePrimitivesSeen.size()=38)

Progress update: steps=0, test inputs generated=0, failing inputs=0      (Sun Feb 03 21:56:30 PST 2019)
Progress update: steps=226, test inputs generated=201, failing inputs=131      (Sun Feb 03 21:56:36 PST 2019)
Normal method executions: 307
Exceptional method executions: 131

Average method execution time (normal termination):      0.0174
Average method execution time (exceptional termination): 0.0915

Error-revealing test output:
Error-revealing test count: 131
Writing JUnit tests...

Created file /Users/Eric/Documents/School/CSE 403/HW3/randoop-4.1.0/ErrorTest0.java
Created file /Users/Eric/Documents/School/CSE 403/HW3/randoop-4.1.0/ErrorTest.java

Regression test output:
Regression test count: 59
Writing JUnit tests...

Failure in commentFailingAssertions(null, RegressionTest0)
javaCode =
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest0 {

    public static boolean debug = false;

    @Test
    public void test01() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test01");
        junit.framework.Assert.assertEquals("hi!", 100.0d, (double) (byte) 100, (double) 0);
    }

    @Test
    public void test02() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test02");
        junit.framework.Assert.assertFalse("hi!", false);
    }

    @Test
    public void test03() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test03");
        junit.framework.Assert.assertNotNull("", (java.lang.Object) 1.0d);
    }

    @Test
    public void test04() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test04");
        junit.framework.Assert.assertEquals("", "");
    }

    @Test
    public void test05() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test05");
        junit.framework.Assert.assertFalse("", false);
    }

    @Test
    public void test06() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test06");
        java.lang.String str3 = junit.framework.Assert.format("hi!", (java.lang.Object) (byte) 1, (java.lang.Object) 10.0d);
        org.junit.Assert.assertTrue("'" + str3 + "' != '" + "hi! expected:<1> but was:<10.0>" + "'", str3.equals("hi! expected:<1> but was:<10.0>"));
    }

    @Test
    public void test07() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test07");
        junit.framework.Assert.assertNotSame((java.lang.Object) 100.0d, (java.lang.Object) (-1.0f));
    }

    @Test
    public void test08() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test08");
        junit.framework.Assert.assertEquals("hi! expected:<1> but was:<10.0>", (float) (short) -1, (float) (short) -1, (float) (byte) 10);
    }

    @Test
    public void test09() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test09");
        java.lang.String str3 = junit.framework.Assert.format("", (java.lang.Object) 10L, (java.lang.Object) 0);
        org.junit.Assert.assertTrue("'" + str3 + "' != '" + "expected:<10> but was:<0>" + "'", str3.equals("expected:<10> but was:<0>"));
    }

    @Test
    public void test10() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test10");
        junit.framework.Assert.assertEquals("hi!", (int) (short) 0, (int) (short) 0);
    }

    @Test
    public void test11() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test11");
        junit.framework.Assert.assertEquals("hi!", (byte) 0, (byte) 0);
    }

    @Test
    public void test12() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test12");
        junit.framework.Assert.assertNotNull("expected:<10> but was:<0>", (java.lang.Object) "");
    }

    @Test
    public void test13() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test13");
        junit.framework.Assert.assertEquals(true, true);
    }

    @Test
    public void test14() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test14");
        junit.framework.Assert.assertNotNull((java.lang.Object) 10L);
    }

    @Test
    public void test15() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test15");
        junit.framework.Assert.assertNotNull("expected:<10> but was:<0>", (java.lang.Object) (-1.0d));
    }

    @Test
    public void test16() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test16");
        junit.framework.Assert.assertEquals((int) (byte) 1, (int) (byte) 1);
    }

    @Test
    public void test17() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test17");
        junit.framework.Assert.assertNotNull("hi!", (java.lang.Object) (byte) 100);
    }

    @Test
    public void test18() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test18");
        junit.framework.Assert.assertEquals((byte) 1, (byte) 1);
    }

    @Test
    public void test19() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test19");
        junit.framework.Assert.assertEquals((short) 0, (short) (byte) 0);
    }

    @Test
    public void test20() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test20");
        junit.framework.Assert.assertEquals("expected:<10> but was:<0>", '#', '#');
    }

    @Test
    public void test21() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test21");
        junit.framework.Assert.assertNotSame((java.lang.Object) "", (java.lang.Object) 0L);
    }

    @Test
    public void test22() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test22");
        junit.framework.Assert.assertTrue(true);
    }

    @Test
    public void test23() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test23");
        junit.framework.Assert.assertNotNull("expected:<10> but was:<0>", (java.lang.Object) 100L);
    }

    @Test
    public void test24() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test24");
        junit.framework.Assert.assertEquals("expected:<10> but was:<0>", (float) (-1), (float) (short) -1, 1.0f);
    }

    @Test
    public void test25() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test25");
        junit.framework.Assert.assertNotNull((java.lang.Object) '4');
    }

    @Test
    public void test26() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test26");
        junit.framework.Assert.assertEquals((double) 0.0f, 100.0d, (double) 100L);
    }

    @Test
    public void test27() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test27");
        java.lang.String str3 = junit.framework.Assert.format("hi! expected:<1> but was:<10.0>", (java.lang.Object) (short) 10, (java.lang.Object) 100);
        org.junit.Assert.assertTrue("'" + str3 + "' != '" + "hi! expected:<1> but was:<10.0> expected:<10> but was:<100>" + "'", str3.equals("hi! expected:<1> but was:<10.0> expected:<10> but was:<100>"));
    }

    @Test
    public void test28() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test28");
        junit.framework.Assert.assertEquals("expected:<10> but was:<0>", true, true);
    }

    @Test
    public void test29() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test29");
        junit.framework.Assert.assertEquals((double) (short) 10, (double) 10.0f, (double) 1.0f);
    }

    @Test
    public void test30() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test30");
        junit.framework.Assert.assertNotNull("expected:<10> but was:<0>", (java.lang.Object) (byte) 1);
    }

    @Test
    public void test31() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test31");
        junit.framework.Assert.assertTrue("hi! expected:<1> but was:<10.0>", true);
    }

    @Test
    public void test32() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test32");
        junit.framework.Assert.assertEquals("expected:<10> but was:<0>", false, false);
    }

    @Test
    public void test33() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test33");
        junit.framework.Assert.assertEquals('4', '4');
    }

    @Test
    public void test34() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test34");
        junit.framework.Assert.assertFalse(false);
    }

    @Test
    public void test35() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test35");
        junit.framework.Assert.assertNotSame((java.lang.Object) 100.0f, (java.lang.Object) 1);
    }

    @Test
    public void test36() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test36");
        java.lang.Object obj1 = new java.lang.Object();
        java.lang.Class<?> wildcardClass2 = obj1.getClass();
        junit.framework.Assert.assertNotNull("hi! expected:<1> but was:<10.0>", (java.lang.Object) wildcardClass2);
        org.junit.Assert.assertNotNull(wildcardClass2);
    }

    @Test
    public void test37() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test37");
        junit.framework.Assert.assertNotSame((java.lang.Object) 100.0f, (java.lang.Object) 0L);
    }

    @Test
    public void test38() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test38");
        junit.framework.Assert.assertEquals(false, false);
    }

    @Test
    public void test39() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test39");
        java.lang.String str3 = junit.framework.Assert.format("expected:<10> but was:<0>", (java.lang.Object) 0.0f, (java.lang.Object) 0);
        org.junit.Assert.assertTrue("'" + str3 + "' != '" + "expected:<10> but was:<0> expected:<0.0> but was:<0>" + "'", str3.equals("expected:<10> but was:<0> expected:<0.0> but was:<0>"));
    }

    @Test
    public void test40() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test40");
        junit.framework.Assert.assertEquals((short) (byte) 100, (short) 100);
    }

    @Test
    public void test41() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test41");
        junit.framework.Assert.assertEquals("", '4', '4');
    }

    @Test
    public void test42() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test42");
        junit.framework.Assert.assertEquals("expected:<10> but was:<0> expected:<0.0> but was:<0>", true, true);
    }

    @Test
    public void test43() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test43");
        junit.framework.Assert.assertEquals("expected:<10> but was:<0> expected:<0.0> but was:<0>", (short) 10, (short) 10);
    }

    @Test
    public void test44() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test44");
        java.lang.Object obj4 = new java.lang.Object();
        java.lang.Class<?> wildcardClass5 = obj4.getClass();
        junit.framework.Assert.assertNotSame("expected:<10> but was:<0>", (java.lang.Object) 10L, obj4);
        java.lang.String str7 = junit.framework.Assert.format("hi! expected:<1> but was:<10.0> expected:<10> but was:<100>", (java.lang.Object) (short) 100, (java.lang.Object) "expected:<10> but was:<0>");
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertTrue("'" + str7 + "' != '" + "hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>>" + "'", str7.equals("hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>>"));
    }

    @Test
    public void test45() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test45");
        junit.framework.Assert.assertEquals("", "hi!", "hi!");
    }

    @Test
    public void test46() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test46");
        junit.framework.Assert.assertEquals("hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>> expected:<class java.lang.Object> but was:<-1.0>", (float) (byte) -1, 0.0f, (float) '#');
    }

    @Test
    public void test47() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test47");
        junit.framework.Assert.assertNotSame((java.lang.Object) (byte) 10, (java.lang.Object) "hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>>");
    }

    @Test
    public void test48() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test48");
        java.lang.Object obj5 = new java.lang.Object();
        junit.framework.Assert.assertNotSame("hi!", (java.lang.Object) (-1L), obj5);
        junit.framework.Assert.assertNotSame((java.lang.Object) 10.0f, obj5);
        junit.framework.Assert.assertNotNull("hi! expected:<1> but was:<10.0>", obj5);
        junit.framework.Assert.assertNotSame((java.lang.Object) 0.0f, (java.lang.Object) "hi! expected:<1> but was:<10.0>");
    }

    @Test
    public void test49() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test49");
        junit.framework.Assert.assertNotNull("", (java.lang.Object) 100);
    }

    @Test
    public void test50() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test50");
        junit.framework.Assert.assertEquals("hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>> expected:<class java.lang.Object> but was:<-1.0>", (byte) 0, (byte) 0);
    }

    @Test
    public void test51() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test51");
        junit.framework.Assert.assertNotNull((java.lang.Object) 1.0d);
    }

    @Test
    public void test52() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test52");
        java.lang.Object obj5 = new java.lang.Object();
        junit.framework.Assert.assertNotSame("hi!", (java.lang.Object) (-1L), obj5);
        junit.framework.Assert.assertNotSame((java.lang.Object) 10.0f, obj5);
        junit.framework.Assert.assertNotNull("hi! expected:<1> but was:<10.0>", obj5);
        java.lang.Class<?> wildcardClass9 = obj5.getClass();
        java.lang.String str11 = junit.framework.Assert.format("hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>>", (java.lang.Object) wildcardClass9, (java.lang.Object) (-1.0d));
        junit.framework.Assert.assertNotNull((java.lang.Object) str11);
        org.junit.Assert.assertNotNull(wildcardClass9);
        org.junit.Assert.assertTrue("'" + str11 + "' != '" + "hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>> expected:<class java.lang.Object> but was:<-1.0>" + "'", str11.equals("hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>> expected:<class java.lang.Object> but was:<-1.0>"));
    }

    @Test
    public void test53() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test53");
        junit.framework.Assert.assertEquals("hi! expected:<1> but was:<10.0>", (float) (short) -1, (float) 0, (float) (short) 1);
    }

    @Test
    public void test54() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test54");
        junit.framework.Assert.assertEquals(10.0d, (double) (short) 10, (double) 1.0f);
    }

    @Test
    public void test55() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test55");
        junit.framework.Assert.assertEquals((float) 10, (float) 10, (float) (byte) 10);
    }

    @Test
    public void test56() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test56");
        junit.framework.Assert.assertEquals("expected:<10> but was:<0>", "", "");
    }

    @Test
    public void test57() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test57");
        java.lang.Object obj1 = new java.lang.Object();
        java.lang.Class<?> wildcardClass2 = obj1.getClass();
        java.lang.Object obj5 = new java.lang.Object();
        junit.framework.Assert.assertNotSame("hi!", (java.lang.Object) (-1L), obj5);
        junit.framework.Assert.assertNotSame("expected:<10> but was:<0>", (java.lang.Object) wildcardClass2, (java.lang.Object) (-1L));
        org.junit.Assert.assertNotNull(wildcardClass2);
    }

    @Test
    public void test58() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test58");
        java.lang.Object obj0 = new java.lang.Object();
        java.lang.Class<?> wildcardClass1 = obj0.getClass();
        junit.framework.Assert.assertNotSame(obj0, (java.lang.Object) "hi! expected:<1> but was:<10.0> expected:<10> but was:<100> expected:<100> but was:<expected:<10> but was:<0>> expected:<class java.lang.Object> but was:<-1.0>");
        org.junit.Assert.assertNotNull(wildcardClass1);
    }

    @Test
    public void test59() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest0.test59");
        java.lang.Object obj4 = new java.lang.Object();
        junit.framework.Assert.assertNotSame("hi!", (java.lang.Object) (-1L), obj4);
        junit.framework.Assert.assertNotSame((java.lang.Object) 10.0f, obj4);
        junit.framework.Assert.assertNotNull("hi! expected:<1> but was:<10.0>", obj4);
        java.lang.Class<?> wildcardClass8 = obj4.getClass();
        java.lang.Class<?> wildcardClass9 = obj4.getClass();
        org.junit.Assert.assertNotNull(wildcardClass8);
        org.junit.Assert.assertNotNull(wildcardClass9);
    }
}

status =
Status for command "java -ea -classpath .:/Users/Eric/Documents/School/CSE 403/HW3/randoop-4.1.0/repo.jar:/Users/Eric/Documents/School/CSE 403/HW3/randoop-4.1.0/randoop-all-4.1.0.jar:/Users/Eric/Documents/School/CSE 403/HW3/randoop-4.1.0/junit.jar org.junit.runner.JUnitCore RegressionTest0" = 1 (timedOut=false), stdout lines=24, stderr=""

Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues .
randoop.BugInRandoopException: Check configuration of test environment: initialization error of test in flaky-test filter: 1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
	at randoop.output.FailingTestFilter.commentFailingAssertions(FailingTestFilter.java:267)
	at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:120)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:600)
	at randoop.main.GenTests.handle(GenTests.java:511)
	at randoop.main.Main.nonStaticMain(Main.java:67)
	at randoop.main.Main.main(Main.java:31)

4. The files used were:
-randoop-all-4.1.0.jar
-junit.jar (the latest junit4 jar from https://search.maven.org/search?q=g:junit%20AND%20a:junit)
-repo.jar (a jar file made from the junit4 repo, https://github.com/junit-team/junit4)

**Comment by mernst** [comment] 2019-02-04 15:42
I'm sorry you are having trouble.  Thanks for the bug report.

You said that `repo.jar` is "a jar file made from the junit4 repo, https://github.com/junit-team/junit4)".  For reproducibility, can you tell us how it was made?  I looked in that repository and don't see any buildfile rules for creating "repo.jar".

**Comment by wahleric** [comment] 2019-02-08 13:51
My apologies, I think I had misunderstood how to set up my class files initially. I had simply created the jar file using the command "jar cf repo.jar junit4/". I see now that the maven build file for the junit4 project includes a maven-jar-plugin, which I have now used via "mvn jar:jar" which creates a "junit-4.13-SNAPSHOT.jar" file. I am now running Randoop with the following command:

Java -Xmx3000m -classpath junit-4.13-SNAPSHOT.jar:randoop-all-4.1.0.jar:junit.jar randoop.main.Main gentests --classlist=../myclasses.txt --output-limit=100 --flaky-test-behavior=DISCARD

For which the output still results in an error (although a different error):

Ignoring abstract class org.junit.internal.ComparisonCriteria specified via --classlist or --testclass.
Ignoring abstract class org.junit.validator.AnnotationValidator specified via --classlist or --testclass.
Ignoring non-visible class org.junit.internal.management.ReflectiveThreadMXBean specified via --classlist or --testclass.
Ignoring non-visible class org.junit.internal.management.FakeThreadMXBean specified via --classlist or --testclass.
Ignoring non-visible class org.junit.internal.management.FakeRuntimeMXBean specified via --classlist or --testclass.
Ignoring non-visible class org.junit.internal.management.ReflectiveRuntimeMXBean specified via --classlist or --testclass.
Ignoring abstract class org.junit.runners.ParentRunner specified via --classlist or --testclass.
Ignoring non-visible class org.junit.runners.RuleContainer specified via --classlist or --testclass.
Ignoring non-visible class org.junit.internal.requests.MemoizingRequest specified via --classlist or --testclass.
Ignoring non-visible class org.junit.runner.FilterFactories specified via --classlist or --testclass.
Ignoring non-visible class org.junit.runner.JUnitCommandLineParseResult specified via --classlist or --testclass.
Ignoring abstract class org.junit.runner.Request specified via --classlist or --testclass.
Ignoring abstract class org.junit.runner.Runner specified via --classlist or --testclass.
Ignoring non-visible class org.junit.internal.runners.rules.ValidationError specified via --classlist or --testclass.
Ignoring abstract class junit.framework.TestCase specified via --classlist or --testclass.
Ignoring abstract class junit.runner.BaseTestRunner specified via --classlist or --testclass.
Ignoring non-visible class org.junit.internal.runners.FailedBefore specified via --classlist or --testclass.
Ignoring abstract class org.junit.runners.model.Statement specified via --classlist or --testclass.
Ignoring non-visible class org.junit.runners.model.NoGenericTypeParametersValidator specified via --classlist or --testclass.
Ignoring abstract class org.junit.runners.model.RunnerBuilder specified via --classlist or --testclass.
Ignoring abstract class org.junit.runners.model.FrameworkMember specified via --classlist or --testclass.
Ignoring non-visible class org.junit.experimental.results.FailureList specified via --classlist or --testclass.
Ignoring non-visible class org.junit.runner.notification.SynchronizedRunListener specified via --classlist or --testclass.
Ignoring abstract class org.junit.experimental.theories.ParameterSupplier specified via --classlist or --testclass.
Ignoring abstract class org.junit.experimental.theories.PotentialAssignment specified via --classlist or --testclass.
Ignoring abstract class org.junit.runner.manipulation.Filter specified via --classlist or --testclass.
Ignoring abstract class org.junit.runner.manipulation.Ordering specified via --classlist or --testclass.
Ignoring abstract class org.junit.rules.Verifier specified via --classlist or --testclass.
Ignoring abstract class org.junit.rules.ExternalResource specified via --classlist or --testclass.
Ignoring non-visible class org.junit.rules.ExpectedExceptionMatcherBuilder specified via --classlist or --testclass.
Ignoring abstract class org.junit.rules.TestWatcher specified via --classlist or --testclass.
Ignoring non-visible class org.junit.experimental.categories.CategoryFilterFactory specified via --classlist or --testclass.
Ignoring abstract class org.junit.internal.matchers.TypeSafeMatcher specified via --classlist or --testclass.
Ignoring abstract class org.junit.internal.runners.model.ReflectiveCallable specified via --classlist or --testclass.
PUBLIC MEMBERS=806
Explorer = randoop.generation.ForwardGenerator(allSequences.size()=0,observers.size()=0,subsumed_sequences.size()=0,runtimePrimitivesSeen.size()=38)

Progress update: steps=1, test inputs generated=0, failing inputs=0      (Fri Feb 08 05:48:38 PST 2019)
Throwable thrown while handling command: java.lang.NullPointerException
java.lang.NullPointerException
	at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:24)
	at org.hamcrest.core.IsCollectionContaining.describeTo(IsCollectionContaining.java:39)
	at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:24)
	at org.hamcrest.BaseDescription.appendList(BaseDescription.java:94)
	at org.hamcrest.BaseDescription.appendList(BaseDescription.java:85)
	at org.hamcrest.core.AllOf.describeTo(AllOf.java:38)
	at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:24)
	at org.junit.internal.AssumptionViolatedException.describeTo(AssumptionViolatedException.java:107)
	at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:24)
	at org.hamcrest.StringDescription.toString(StringDescription.java:28)
	at org.hamcrest.StringDescription.asString(StringDescription.java:35)
	at org.junit.internal.AssumptionViolatedException.getMessage(AssumptionViolatedException.java:88)
	at randoop.test.ExpectedExceptionCheck.appendTryBehavior(ExpectedExceptionCheck.java:48)
	at randoop.test.ExceptionCheck.toCodeStringPostStatement(ExceptionCheck.java:106)
	at randoop.sequence.ExecutableSequence.toCodeLines(ExecutableSequence.java:173)
	at randoop.sequence.ExecutableSequence.toCodeString(ExecutableSequence.java:199)
	at randoop.output.JUnitCreator.createTestMethod(JUnitCreator.java:293)
	at randoop.output.JUnitCreator.createTestClass(JUnitCreator.java:249)
	at randoop.test.CompilableTestPredicate.test(CompilableTestPredicate.java:75)
	at randoop.test.CompilableTestPredicate.test(CompilableTestPredicate.java:18)
	at java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:325)
	at randoop.main.GenTests.handle(GenTests.java:456)
	at randoop.main.Main.nonStaticMain(Main.java:67)
	at randoop.main.Main.main(Main.java:31)

Randoop failed.
Last sequence under execution:
java.lang.Iterable<java.lang.CharSequence> charSequenceIterable1 = null;
org.hamcrest.Matcher<? super java.lang.CharSequence> wildcardMatcher2 = null;
org.hamcrest.Matcher[] matcherArray4 = new org.hamcrest.Matcher[ 1 ];
@SuppressWarnings("unchecked")
org.hamcrest.Matcher<? super java.lang.CharSequence>[] wildcardMatcherArray5 = (org.hamcrest.Matcher<? super java.lang.CharSequence>[])matcherArray4;
wildcardMatcherArray5[0] = wildcardMatcher2;
org.hamcrest.Matcher<java.lang.Iterable<java.lang.CharSequence>> charSequenceIterableMatcher8 = org.junit.matchers.JUnitMatchers.hasItems(wildcardMatcherArray5);
org.junit.Assume.assumeThat("hi!", charSequenceIterable1, charSequenceIterableMatcher8);

**Comment by mernst** [comment] 2019-02-10 00:32
I'm sorry you are still having trouble.  Unfortunately, I cannot reproduce your problem, because you did not provide the `myclasses.txt` file.
Can you please provide a reproducible recipe for reproducing the problem?
There is [guidance about bug reporting](https://randoop.github.io/randoop/manual/index.html#bug-reporting) in the Randoop manual.
Thanks!

**Comment by mernst** [comment] 2019-02-21 00:12
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2019-02-21 00:12 UTC
Labels: unreproducible
