### ISSUE TITLE
mac terminal run fail

### ISSUE THREAD

**Issue by zdjniubi** [randoop/randoop#953] opened 2021-07-20 04:59 UTC
zdj@DJEOZHANG-MB0 test1 % java randoop.main.Main gentests --classlist=myclasses.txt --time-limit=60 
Randoop for Java version 4.2.6.

Throwable thrown while handling command: java.lang.IllegalArgumentException: Path component should be '/'
java.lang.IllegalArgumentException: Path component should be '/'
	at java.base/sun.nio.fs.UnixFileSystemProvider.checkUri(UnixFileSystemProvider.java:82)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileSystem(UnixFileSystemProvider.java:91)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:338)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:287)
	at randoop.main.GenTests.getResourceDirectoryPath(GenTests.java:1315)
	at randoop.main.GenTests.getJDKSpecificationFiles(GenTests.java:1284)
	at randoop.main.GenTests.handle(GenTests.java:304)
	at randoop.main.Main.nonStaticMain(Main.java:71)
	at randoop.main.Main.main(Main.java:31)

Randoop failed.
No sequences generated.

help

**Comment by mernst** [comment] 2021-07-20 14:27
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  Can you please provide all the details that were requested in the [issue template](https://github.com/randoop/randoop/issues/new) and the [bug reporting section of the manual](https://randoop.github.io/randoop/manual/#bug-reporting)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!

**Comment by mernst** [comment] 2021-07-28 19:23
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2021-07-28 19:23 UTC
Labels: unreproducible
