### ISSUE TITLE
Randoop (feeded with specifications) failed in unexpected way

### ISSUE THREAD

**Issue by ariannab** [randoop/randoop#346] opened 2018-04-27 15:12 UTC
While executing Randoop version 4.0.3 I get the following error:

```
Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues .
randoop.BugInRandoopException: Error during generation: Failure executing expression method: public static boolean org.apache.commons.collections4.iterators.RandoopExpressionClass690.MethodNameIsIrrelevant(org.w3c.dom.Node) throws java.lang.Throwable: java.lang.NullPointerException
        at randoop.main.GenTests.handle(GenTests.java:466)
        at randoop.main.Main.nonStaticMain(Main.java:65)
        at randoop.main.Main.main(Main.java:29)
Caused by: randoop.condition.RandoopConditionError: Failure executing expression method: public static boolean org.apache.commons.collections4.iterators.RandoopExpressionClass690.MethodNameIsIrrelevant(org.w3c.dom.Node) throws java.lang.Throwable: java.lang.NullPointerException
        at randoop.condition.ExecutableBooleanExpression.check(ExecutableBooleanExpression.java:141)
        at randoop.condition.ExecutableSpecification.checkPreExpressions(ExecutableSpecification.java:120)
        at randoop.condition.ExecutableSpecification.checkPrestate(ExecutableSpecification.java:104)
        at randoop.condition.ExecutableSpecification.checkPrestate(ExecutableSpecification.java:80)
        at randoop.operation.TypedOperation.checkPrestate(TypedOperation.java:586)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:290)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:228)
        at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:138)
        at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:299)
        at randoop.main.GenTests.handle(GenTests.java:454)
        ... 2 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at randoop.condition.ExecutableBooleanExpression.check(ExecutableBooleanExpression.java:132)
        ... 11 more
Caused by: java.lang.NullPointerException
        at org.apache.commons.collections4.iterators.RandoopExpressionClass690.MethodNameIsIrrelevant(RandoopExpressionClass690.java:5)
        ... 16 more
```

The base command is the following:
```
java -ea -cp commons-collections4-4.1.jar:randoop.jar randoop.main.Main gentests 
--classlist=evallist.txt 
--time-limit=900
--stop-on-error-test 
--junit-output-dir=./src/test/java 
--flaky-test-behavior=DISCARD 
--no-regression-tests 
--log=randoop-log.tx
```
Then I have to pass many specifications via option `--specifications`.

To reproduce the command you need: 

The file [evallist.txt](https://github.com/randoop/randoop/files/1955622/evallist.txt) 

All the specifications in JSON format: [specifications.zip](https://github.com/randoop/randoop/files/1955618/specifications.zip)

And the `commons-collections4-4.1.jar` file: http://central.maven.org/maven2/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar

**Comment by mernst** [comment] 2018-04-29 22:06
I could not reproduce your problem.

Here is the command I ran:
(You should pull and recompile Randoop before running this.)

```
java -ea -cp commons-collections4-4.1.jar:$RANDOOP_HOME/build/libs/randoop-all-4.0.3.jar randoop.main.Main gentests \
--classlist=evallist.txt \
--time-limit=900 \
--stop-on-error-test \
--junit-output-dir=./src/test/java \
--flaky-test-behavior=DISCARD \
--no-regression-tests \
--log=randoop-log.txt \
--specifications=specifications.zip
```

The output is:

```
Error in specifications: Duplicate name "target" in specification: { "operation": {
 "classname": "java.awt.BorderLayout",
 "name": "getLayoutComponent",
 "parameterTypes": "[java.awt.Container, java.lang.Object]"
}, "identifiers": { "receiverName": "target", "parameters": [ "target", "constraints"], "returnName": "result" }, "preSpecifications": [] }, "postSpecifications": [], "throwsSpecifications": [{ "description": "@throws java.lang.NullPointerException the target parameter is null.", "guard": "{ "description": "the target parameter is null.", "conditionSource": "target==null" }, "exceptionType": java.lang.NullPointerException" }] while reading file /specifications/java-awt-BorderLayout.json
```

Can you fix the incorrect specifications and try to reproduce your problem?

**Comment by mernst** [comment] 2018-04-30 15:14
Using your new `specifications.zip` file, I can reproduce the problem.  Thanks!

**Comment by mernst** [comment] 2018-05-02 16:07
Also, the translation is wrong and should be

    node.hasChildNodes()) && ((node==null) == false)

This is in addition to the need to guard field/method dereferences.

**Comment by mernst** [comment] 2018-05-04 16:00
I'm closing this because the real problems were:
 * invalid specifications passed to Randoop
 * poor diagnostics from Randoop

Randoop's diagnostics have now been improved.

**Closed by mernst** 2018-05-04 16:00 UTC
