### ISSUE TITLE
Uncompilable sequences generated

### ISSUE THREAD

**Issue by sriramvaliveti** [randoop/randoop#940] opened 2021-06-15 05:27 UTC
When running randoop for a simple Java class shown below, randoop gives _Uncompilable Sequences generated_ and doesnt generate any test classes.
![image](https://user-images.githubusercontent.com/46837422/121997607-40d84280-cdc8-11eb-858c-ae5fb27fc3fe.png)

`public class Test{
	
	public int add(int a, int b){
		return a+b;
	}
}
`

**Comment by mernst** [comment] 2021-06-15 14:34
I'm sorry you are having trouble.  Unfortunately, your bug report is incomplete and unclear.  Could you correct it so we can help you?

You said you ran Randoop on class `Test`, but you didn't show the command you ran.  The command line in your screenshot that is about to be run would run Randoop running on `TreeSet`.

Can you please provide all the details that were requested in the [issue template](https://github.com/randoop/randoop/issues/new) and the [bug reporting section of the manual](https://randoop.github.io/randoop/manual/#bug-reporting)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!

**Comment by mernst** [comment] 2021-06-21 19:41
Ping:  Could you please provide details so we can reproduce your problem, fix it, and verify the fix?

Thank you!

**Comment by mernst** [comment] 2021-06-28 18:17
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2021-06-28 18:17 UTC
Labels: unreproducible
