### ISSUE TITLE
Randoop failed in an unexpected way

### ISSUE THREAD

**Issue by CandiceMeow** [randoop/randoop#426] opened 2019-02-10 06:00 UTC
Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues .
randoop.main.RandoopBug: Check configuration of test environment: initialization error of test in flaky-test filter: 1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
	at randoop.output.FailingTestFilter.commentFailingAssertions(FailingTestFilter.java:267)
	at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:120)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:601)
	at randoop.main.GenTests.handle(GenTests.java:512)
	at randoop.main.Main.nonStaticMain(Main.java:66)
	at randoop.main.Main.main(Main.java:30)

**Comment by mernst** [comment] 2019-02-10 08:47
I'm sorry you are having trouble.
We cannot help you, because this bug report doesn't provide information about how to reproduce the bug.
Those [instructions](https://randoop.github.io/randoop/manual/index.html#bug-reporting) appear in the manual and were also in the template that you deleted in order to paste (part of) the Randoop output.

Could you please provide a full bug report, so that we can help you?

**Comment by mernst** [comment] 2019-02-21 00:12
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2019-02-21 00:12 UTC
Labels: unreproducible
