### ISSUE TITLE
Cannot instantiate non-visible class specified via --testclass or --classlist.

### ISSUE THREAD

**Issue by nitbhu95** [randoop/randoop#917] opened 2021-05-17 09:18 UTC
I am using Randoop latest version 4.2.6 and I am facing an issue and my java version  is 12, Cannot instantiate non-visible classname specified via --testclass or --classlist. I have seen troubleshooting section but it didnt helped me .
This is my simple code which is present in /home/niteshb/Downloads/randoop-4.2.6/Welcomes.class

```

class Welcomes {

	public static int addmethod(int a, int b) {
		int z = a + b;

		return z;
	}

	public static void main(String[] args) {
		addmethod(10, 20);
	}
}
```

now I am trying to execute command :-1: 
`java -classpath /home/niteshb/Downloads/randoop-4.2.6:/home/niteshb/Downloads/randoop-4.2.6/randoop-all-4.2.6.jar randoop.main.Main gentests --testclass=Welcomes --literals-file=CLASSES`

but I am getting an error as 
```
Cannot instantiate non-visible Welcomes specified via --testclass or --classlist.

Will try to generate tests for 0 out of 1 classes.
You provided no methods to test, so no tests for them can be generated.

Additional diagnostis appear below.
Model with hashcode 243745864:
  classTypes = [java.lang.Object]
  inputTypes = []
  coveredClassesGoal = []
  classLiteralMap = {}
  annotatedTestValues = []
  contracts = ContractSet[size=12]
    arity 1: [randoop.contract.EqualsReflexive@29b5cd00, randoop.contract.EqualsToNullRetFalse@60285225, randoop.contract.EqualsReturnsNormally@7113b13f, randoop.contract.CompareToReflexive@45820e51, randoop.contract.SizeToArrayLength@42d8062c]
    arity 2: [randoop.contract.EqualsSymmetric@6043cd28, randoop.contract.EqualsHashcode@cb51256, randoop.contract.CompareToAntiSymmetric@59906517, randoop.contract.CompareToEquals@5bfbf16f]
    arity 3: [randoop.contract.EqualsTransitive@25af5db5, randoop.contract.CompareToSubs@12cdcf4, randoop.contract.CompareToTransitive@5bcea91b]
  omitMethods = [
    \bensuresCapacity\b
    ^\Qcom.google.common.collect.Iterators.cycle(
    ^\Qorg.apache.commons.math4.genetics.GeneticAlgorithm.getRandomGenerator()\E$
    ^\Qorg.apache.commons.math4.util.FastMath.random()\E$
    ^\Qjava.util.Date.<init>()\E$
    ^\Qorg.joda.time.DateTime.now()\E$
    ^\Qorg.joda.time.LocalDate.<init>\E$
    ^\Qnew org.joda.time.Partial.<init>()\E$
    ^\Qjava.io.File.list()\E$
    ^\Qjava.io.File.list(java.io.FilenameFilter)\E$
    ^\Qjava.io.File.listFiles()\E$
    ^\Qjava.io.File.listFiles(java.io.FileFilter)\E$
    ^\Qjava.io.File.listFiles(java.io.FilenameFilter)\E$
    ^\Qjava.io.File.listRoots()\E$
    ^\Qjava.lang.Class.getSigners()\E$
    ^\Qjava.lang.Object.hashCode()\E$
    ^\Qjava.lang.String.hashCode()\E$
    ^\Qjava.lang.System.clearProperty(java.lang.String)\E$
    ^\Qjava.lang.System.console()\E$
    ^\Qjava.lang.System.currentTimeMillis()\E$
    ^\Qjava.lang.System.getProperties()\E$
    ^\Qjava.lang.System.getProperty(java.lang.String)\E$
    ^\Qjava.lang.System.getProperty(java.lang.String, java.lang.String)\E$
    ^\Qjava.lang.System.getSecurityManager()\E$
    ^\Qjava.lang.System.getenv()\E$
    ^\Qjava.lang.System.getenv(java.lang.String)\E$
    ^\Qjava.lang.System.identityHashCode(java.lang.Object)\E$
    ^\Qjava.lang.System.inheritedChannel()\E$
    ^\Qjava.lang.System.mapLibraryName(java.lang.String)\E$
    ^\Qjava.lang.System.nanoTime()\E$
    ^\Qjava.lang.System.setProperty(java.lang.String, java.lang.String)\E$
    ^\Qjava.lang.reflect.Method.hashCode()\E$
    ^\Qjava.text.BreakIterator.getAvailableLocales()\E$
    ^\Qjava.util.AbstractList.hashCode()\E$
    ^\Qjava.util.AbstractSet.hashCode()\E$
    ^\Qjava.util.Arrays.deepHashCode(java.lang.Object[])\E$
    ^\Qjava.util.Arrays.hashCode(boolean[])\E$
    ^\Qjava.util.Arrays.hashCode(byte[])\E$
    ^\Qjava.util.Arrays.hashCode(char[])\E$
    ^\Qjava.util.Arrays.hashCode(double[])\E$
    ^\Qjava.util.Arrays.hashCode(float[])\E$
    ^\Qjava.util.Arrays.hashCode(int[])\E$
    ^\Qjava.util.Arrays.hashCode(java.lang.Object[])\E$
    ^\Qjava.util.Arrays.hashCode(long[])\E$
    ^\Qjava.util.Arrays.hashCode(short[])\E$
    ^\Qjava.util.Collection.hashCode()\E$
    ^\Qjava.util.Collections.shuffle(java.util.List)\E$
    ^\Qjava.util.Comparator.compare(java.lang.Object, java.lang.Object)\E$
    ^\Qjava.util.List.hashCode()\E$
    ^\Qjava.util.Random.<init>()\E$
    ^\Qjava.util.Set.hashCode()\E$
  ]
Operations: (1)
  java.lang.Object.<init> : () -> java.lang.Object

There are no methods for Randoop to test.  See diagnostics above.  Exiting.

```
can someone guide whats going wrong here ..???

**Comment by mernst** [comment] 2021-05-18 15:06
I'm sorry you are having trouble.  Thanks for getting in touch.

The problem is that class `Welcomes` is not public.  If you make it public, then Randoop will generate tests for it.

For your information, I determined this by following the instructions in the Randoop manual, section "Randoop does not create enough tests, or creates no tests".  Please read the documentation before asking questions; that will likely save time.

**Comment by mernst** [comment] 2021-06-14 21:19
I'm closing this because the original poster has not responded.

**Closed by mernst** 2021-06-14 21:19 UTC
