### ISSUE TITLE
Spring DI support for Spring boot project

### ISSUE THREAD

**Issue by Ajar-Susey** [randoop/randoop#808] opened 2020-09-25 07:03 UTC
As a Java software developer I want to make the Randoop workable with bean injection in Spring framework.

**Comment by mernst** [comment] 2020-09-25 17:14
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  Can you please provide all the details that were requested in the [issue template](https://github.com/randoop/randoop/issues/new) and the [bug reporting section of the manual](https://randoop.github.io/randoop/manual/#bug-reporting)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!

**Comment by mernst** [comment] 2020-10-05 03:01
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2020-10-05 03:01 UTC
Labels: unreproducible
