### ISSUE TITLE
ReplaceCallAgent.getJarPathFromURL(URL) with Windows environment

### ISSUE THREAD

**Issue by VincentBUBU** [randoop/randoop#856] opened 2021-01-20 06:00 UTC
Hello,

I try to use randoop, with replacecall, to generate a test suite, but I meet an unexpected exception.

---

My configuration is:

**Version of Randoop:** randoop-4.2.5 + replacecall-4.2.5

**Java Version:**
```batch
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-win64) (build 1.8.0_252-b14)
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-win64) (build 25.252-b14, mixed mode)
```

**Operating system version:** Microsoft Windows 7

**Command:** 
```batch
java -ea -classpath ... -Xbootclasspath/a:D:\replacecall-4.2.5.jar -javaagent:D:\replacecall-4.2.5.jar randoop.main.Main gentests --time-limit=40 --testclass=...
```

**Output:**
```batch
Unexpected exception thrown by replacecall agent: Illegal char <:> at index 2: /D:/replacecall-4.2.5.jar
```
---
Please find my first analysis.

By debugging, I found the following stack:
```java
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/replacecall-4.2.5.jar
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at randoop.instrument.ReplacementFileReader.addReplacementsForPackage(ReplacementFileReader.java:399)
        at randoop.instrument.ReplacementFileReader.addReplacementsForClassOrPackage(ReplacementFileReader.java:258)
        at randoop.instrument.ReplacementFileReader.readReplacements(ReplacementFileReader.java:137)
        at randoop.instrument.ReplaceCallAgent.premain(ReplaceCallAgent.java:156)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```
I think that the issue is in the method `ReplaceCallAgent.getJarPathFromURL(URL)` because, for me, Windows paths are not correctly managed.
```java
protected static String getJarPathFromURL(URL url) {
    String jarPath = url.getPath();
    return jarPath.substring(jarPath.indexOf(":") + 1, jarPath.indexOf("!"));
}
```
In my case, the value of `jarPath` is: `jar:file:/D:/replacecall-4.2.5.jar!/default-replacements.txt`

For Windows environment, the start index (`jarPath.indexOf(":") + 1`) is wrong.

**Comment by mernst** [comment] 2021-01-20 17:56
Thanks for reporting this problem, and for your accurate diagnosis of the problem.  (And my apologies that you encountered it!)

I have pushed a fix that I believe corrects the problem.  Could you verify that this works for you under Windows?

**Comment by VincentBUBU** [comment] 2021-01-20 20:32
Thanks for your responsiveness, but unfortunately the modification doesn't correct my issue.
With my Windows, the value of `System.getProperty("path.separator")` is `;`.
I will try to submit to you a solution.

**Comment by markro49** [comment] 2021-01-20 23:30
I think a couple things are going on here.  First, we are looking for a URL separator, not a path separator.  The former is ":" in all environments.  My guess is the problem is the extra "/" windows puts at the start of the path (before the D:).  So fix might be to check to see if the "os.name" property starts with "Windows" and if it does, add 2 not 1 to index of ":".

**Comment by VincentBUBU** [comment] 2021-01-21 20:10
I tried to find a solution which is not dependent on substrings.
I found the following code:
```java
final URLConnection urlConnection = url.openConnection();
final JarURLConnection jarURLConnection = (JarURLConnection) urlConnection;
jarPathFromURL = Paths.get(jarURLConnection.getJarFileURL().toURI()).toString();
```
It works on Windows, not tested on Linux.
In this code snippet, the following items are not managed:
- Check before JarURLConnection cast -> risk of ClassCastException
- Exceptions thrown by:
    - URL.openConnection() -> IOException
    - URL.toURI() -> URISyntaxException

**Comment by markro49** [comment] 2021-01-28 19:08
fixed with https://github.com/randoop/randoop/pull/858

**Closed by markro49** 2021-01-28 19:08 UTC
