### ISSUE TITLE
toCodeString() removes assignments to primitive wrappers when allowShortForm == true

### ISSUE THREAD

**Issue by SnowOnion** [randoop/randoop#360] opened 2018-05-11 07:34 UTC
Randoop version: current latest commit on `master` branch https://github.com/randoop/randoop/commit/8a26ba98814376a29080350d450d063e09d757bb.

We know that `Sequence#toCodeString()` and `ExecutableSequence #toCodeString()` give shortened form of a sequence, when `Sequence#allowShortForm == True`. However sometimes they went wrong.

This sequence should not be shortened:
```java
java.lang.Float float0 = 10.0f;
boolean boolean1 = float0.isNaN();
```
But when `Sequence#allowShortForm == True`, the `Sequence#toCodeString()` and `ExecutableSequence#toCodeString()` both mistakenly shorten it to:
```java
boolean boolean1 = float0.isNaN();
```

Test code:

```java
import org.junit.Test;
import randoop.operation.TypedClassOperation;
import randoop.operation.TypedOperation;
import randoop.sequence.ExecutableSequence;
import randoop.sequence.Sequence;
import randoop.types.Type;

public class ShortFormTest {
  @Test
  public void only_float0_isNaN() throws NoSuchMethodException {
    TypedOperation declFloat =
        TypedOperation.createPrimitiveInitialization(Type.forClass(Float.class), 10.0f);
    TypedClassOperation callIsNaN = TypedOperation.forMethod(Float.class.getMethod("isNaN"));

    Sequence s = new Sequence();
    s = s.extend(declFloat);
    s = s.extend(callIsNaN, s.getVariable(0));
    ExecutableSequence es = new ExecutableSequence(s);

    System.out.println(">>> ExecutableSequence.toCodeString() when allowShortForm == true ");
    System.out.println(es.toCodeString());
    System.out.println(">>> Sequence#toCodeString() when allowShortForm == true");
    System.out.println(s.toCodeString()); //  Sequence#toString = Sequence#toCodeString
    s.disableShortForm();

    System.out.println(">>> Sequence#toCodeString() when allowShortForm == false");
    System.out.println(s.toCodeString());
    System.out.println(
        ">>> ExecutableSequence.toCodeString() when es.sequence.allowShortForm == false ");
    System.out.println(es.toCodeString());
  }
}
```

Output:
```
>>> ExecutableSequence.toCodeString() when allowShortForm == true 
boolean boolean1 = float0.isNaN();

>>> Sequence#toCodeString() when allowShortForm == true
boolean boolean1 = float0.isNaN();

>>> Sequence#toCodeString() when allowShortForm == false
java.lang.Float float0 = 10.0f;
boolean boolean1 = float0.isNaN();

>>> ExecutableSequence.toCodeString() when es.sequence.allowShortForm == false 
java.lang.Float float0 = 10.0f;
boolean boolean1 = float0.isNaN();
```

**Comment by mernst** [comment] 2018-05-19 18:13
Thanks for the bug report.
You have provided a test case with a manually-constructed test.
Can you please provide an end-to-end test case, in which a Randoop command-line execution produces non-compilable output?  I wasn't able to do this, but you probably have an example.
Thanks!

**Comment by mernst** [comment] 2018-05-19 18:57
Also, if you pull from master, note that I changed some variable/method names to make them more descriptive.

**Comment by mernst** [comment] 2018-06-10 21:49
I'm closing this because the original poster did not respond with a reproducible test case.

**Closed by mernst** 2018-06-10 21:49 UTC
Labels: unreproducible
