### ISSUE TITLE
Generating Test cases for Spring Boot Service

### ISSUE THREAD

**Issue by Yogeshmsharma-architect** [randoop/randoop#706] opened 2020-02-28 05:17 UTC
I was trying to generate test cases for my sprint boot application which internally usages Spring batch.
It is not able to generate a test case for my Tasklet of spring batch, error thrown was not valid class name. Tasklet generates inner class and names them as $1. 
Is there any workaround exists?

**Comment by mernst** [comment] 2020-03-01 18:21
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  Can you please provide all the details that were requested in the [issue template](https://github.com/randoop/randoop/issues/new) and the [https://randoop.github.io/randoop/manual/#bug-reporting](bug reporting section of the manual)?  This will enable us to reproduce the problem, fix it, and verify the fix.  Thanks!

**Comment by mernst** [comment] 2020-03-09 03:23
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2020-03-09 03:23 UTC
Labels: unreproducible
