### ISSUE TITLE
createAndClassifySequences throw an exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by Ahmedfir** [randoop/randoop#595] opened 2019-09-17 15:56 UTC
I am trying to generate tests for mockito jar library and randoop is failing after around 5 minutes of running because of NPE. Even if I tried to ommit the methods where it crashes, it crashes on other ones... 

randoop output:
```
createAndClassifySequences throw an exception
java.lang.NullPointerException
        at org.mockito.internal.util.reflection.GenericMetadataSupport$WildCardBoundedType.firstBound(GenericMetadataSupport.java:657)
        at org.mockito.internal.util.reflection.GenericMetadataSupport$WildCardBoundedType.toString(GenericMetadataSupport.java:686)
        at java.base/java.lang.String.valueOf(String.java:3042)
        at java.base/java.util.Arrays.toString(Arrays.java:5134)
        at randoop.org.plumelib.util.ArraysPlume.toString(ArraysPlume.java:2106)
        at randoop.operation.MethodCall.execute(MethodCall.java:171)
        at randoop.operation.TypedOperation.execute(TypedOperation.java:273)
        at randoop.sequence.Statement.execute(Statement.java:163)
        at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:405)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:302)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:230)
        at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:211)
        at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:304)
        at randoop.main.GenTests.handle(GenTests.java:467)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)
java.lang.NullPointerException
        at org.mockito.internal.util.reflection.GenericMetadataSupport$WildCardBoundedType.firstBound(GenericMetadataSupport.java:657)
        at org.mockito.internal.util.reflection.GenericMetadataSupport$WildCardBoundedType.toString(GenericMetadataSupport.java:686)
        at java.base/java.lang.String.valueOf(String.java:3042)
        at java.base/java.util.Arrays.toString(Arrays.java:5134)
        at randoop.org.plumelib.util.ArraysPlume.toString(ArraysPlume.java:2106)
        at randoop.operation.MethodCall.execute(MethodCall.java:171)
        at randoop.operation.TypedOperation.execute(TypedOperation.java:273)
        at randoop.sequence.Statement.execute(Statement.java:163)
        at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:405)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:302)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:230)
        at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:211)
        at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:304)
        at randoop.main.GenTests.handle(GenTests.java:467)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)

Throwable thrown while handling command: java.lang.NullPointerException
java.lang.NullPointerException
        at org.mockito.internal.util.reflection.GenericMetadataSupport$WildCardBoundedType.firstBound(GenericMetadataSupport.java:657)
        at org.mockito.internal.util.reflection.GenericMetadataSupport$WildCardBoundedType.toString(GenericMetadataSupport.java:686)
        at java.base/java.lang.String.valueOf(String.java:3042)
        at java.base/java.util.Arrays.toString(Arrays.java:5134)
        at randoop.org.plumelib.util.ArraysPlume.toString(ArraysPlume.java:2106)
        at randoop.operation.MethodCall.execute(MethodCall.java:171)
        at randoop.operation.TypedOperation.execute(TypedOperation.java:273)
        at randoop.sequence.Statement.execute(Statement.java:163)
        at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:405)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:302)
        at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:230)
        at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:211)
        at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:304)
        at randoop.main.GenTests.handle(GenTests.java:467)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)

Randoop failed.
Last sequence under execution: 
org.mockito.internal.junit.UnusedStubbingsFinder unusedStubbingsFinder0 = new org.mockito.internal.junit.UnusedStubbingsFinder();
org.mockito.internal.util.collections.HashCodeAndEqualsSafeSet hashCodeAndEqualsSafeSet1 = new org.mockito.internal.util.collections.HashCodeAndEqualsSafeSet();
org.mockito.internal.junit.UnusedStubbings unusedStubbings2 = unusedStubbingsFinder0.getUnusedStubbings((java.lang.Iterable<java.lang.Object>)hashCodeAndEqualsSafeSet1);
hashCodeAndEqualsSafeSet1.clear();
org.mockito.internal.matchers.LocalizedMatcher[] localizedMatcherArray4 = new org.mockito.internal.matchers.LocalizedMatcher[] {  };
java.util.ArrayList<org.mockito.internal.matchers.LocalizedMatcher> localizedMatcherList5 = new java.util.ArrayList<org.mockito.internal.matchers.LocalizedMatcher>();
boolean boolean6 = java.util.Collections.addAll((java.util.Collection<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList5, localizedMatcherArray4);
java.util.List<org.mockito.invocation.Invocation> invocationList7 = org.mockito.internal.invocation.finder.VerifiableInvocationsFinder.find((java.util.List<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList5);
java.util.Collection<org.mockito.internal.matchers.LocalizedMatcher> localizedMatcherCollection9 = org.mockito.internal.util.Checks.checkItemsNotNull((java.util.Collection<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList5, "");
boolean boolean10 = hashCodeAndEqualsSafeSet1.retainAll((java.util.Collection<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList5);
org.mockito.internal.matchers.LocalizedMatcher[] localizedMatcherArray11 = new org.mockito.internal.matchers.LocalizedMatcher[] {  };
java.util.ArrayList<org.mockito.internal.matchers.LocalizedMatcher> localizedMatcherList12 = new java.util.ArrayList<org.mockito.internal.matchers.LocalizedMatcher>();
boolean boolean13 = java.util.Collections.addAll((java.util.Collection<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList12, localizedMatcherArray11);
java.util.List<org.mockito.invocation.Invocation> invocationList14 = org.mockito.internal.invocation.finder.VerifiableInvocationsFinder.find((java.util.List<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList12);
org.mockito.internal.InOrderImpl inOrderImpl15 = new org.mockito.internal.InOrderImpl((java.util.List<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList12);
boolean boolean16 = hashCodeAndEqualsSafeSet1.addAll((java.util.Collection<org.mockito.internal.matchers.LocalizedMatcher>)localizedMatcherList12);
java.lang.reflect.WildcardType wildcardType17 = null;
org.mockito.internal.util.reflection.GenericMetadataSupport.WildCardBoundedType wildCardBoundedType18 = new org.mockito.internal.util.reflection.GenericMetadataSupport.WildCardBoundedType(wildcardType17);
org.mockito.internal.util.reflection.GenericMetadataSupport.BoundedType[] boundedTypeArray19 = new org.mockito.internal.util.reflection.GenericMetadataSupport.BoundedType[] { wildCardBoundedType18 };
org.mockito.internal.util.reflection.GenericMetadataSupport.BoundedType[] boundedTypeArray20 = hashCodeAndEqualsSafeSet1.toArray(boundedTypeArray19);

```

The version of Randoop: 4.2.0 ,
 the output of `java -version`:
```
java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

, and the operating system version:
MacOS 10.14.6

The command that I run: 
java -classpath /Users/ahmed.khanfir/.m2/repository/randoop/randoop-all/4.2.0/randoop-all-4.2.0.jar:/Users/ahmed.khanfir/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/ahmed.khanfir/IdeaProjects/mockito/build/libs/mockito-core-3.0.8.jar:/Users/ahmed.khanfir/Downloads/jar_files/objenesis-2.6.jar:/Users/ahmed.khanfir/Downloads/jar_files/generics-resolver-3.0.0.jar:/Users/ahmed.khanfir/Downloads/jar_files/scalactic_2.12-3.0.8.jar:/Users/ahmed.khanfir/Downloads/jar_files/scala-reflect-2.12.9.jar:/Users/ahmed.khanfir/Downloads/jar_files/byte-buddy-1.9.10.jar:/Users/ahmed.khanfir/Downloads/jar_files/scala-library-2.12.9.jar:/Users/ahmed.khanfir/Downloads/jar_files/byte-buddy-agent-1.9.10.jar:/Users/ahmed.khanfir/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.1.1/efd9f971e91074491ea55b19f67b13470cf4fcdd/opentest4j-1.1.1.jar randoop.main.Main gentests --omitmethods-file=/Users/ahmed.khanfir/IdeaProjects/scripts/randoop_generate_tests/mockito/randoop_gentests_mockito_omitmethods-file.txt --npe-on-non-null-input=ERROR --log=log_randoop_gentests_mockito-core-3.0.8_jar.txt --time-limit=2400 --flaky-test-behavior=DISCARD --testjar=/Users/ahmed.khanfir/IdeaProjects/mockito/build/libs/mockito-core-3.0.8.jar --testsperfile=250 --junit-package-name=randoop.mockito --junit-output-dir=/Users/ahmed.khanfir/IdeaProjects/mockito/src/test/java

PS: everything is with relative paths.
I am building mockito locally to don't exclude one of its classes.
So here's the output jar: 

[mockito-core-3.0.8.jar.zip](https://github.com/randoop/randoop/files/3622360/mockito-core-3.0.8.jar.zip)

**Comment by mernst** [comment] 2020-01-17 16:09
I'm sorry you are having trouble.   I would like to help you, but I cannot reproduce your problem.
The command you provided uses 12 `.jar` files, but you only provided one of them.  You also did not provide the file `randoop_gentests_mockito_omitmethods-file.txt`.  Could you please simplify the command line if possible, then provide all the files that are needed to reproduce your problem?

**Comment by mernst** [comment] 2020-02-03 06:43
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2020-02-03 06:43 UTC
Labels: unreproducible

**Comment by Ahmedfir** [comment] 2020-02-03 10:08
Sorry for answering so late. I have tried that a couple of months ago. For the 12 libraries I am providing as classpath, I was doing it because the mockito one (AUT) needs them (I guess that was the reason). You're right I should have provided the links to these libraries... 
Sorry again, if my feedback is not helping at all... Thanks for your time and effort.

**Comment by Ahmedfir** [comment] 2020-02-03 10:09
I confirm that this ticket can be closed as unreproducible.

**Comment by mernst** [comment] 2020-02-03 16:45
Thanks for confirming.  If you re-encounter the problem, please let us know and we'll do our best to help you.
