### ISSUE TITLE
Randoop 2.1.0 generates a test case that fails compilation

### ISSUE THREAD

**Issue by jgaleotti** [randoop/randoop#78] opened 2016-01-19 17:45 UTC
The following test case was automatically generated with Randoop . 

 @Test
 public void test076() throws Throwable {

   if (debug) { System.out.format("%n%s%n","RegressionTest1.test076"); }

   org.jfree.data.xy.XYSeries xYSeries2 = new org.jfree.data.xy.XYSeries((java.lang.Comparable)' ', false);
   xYSeries2.add(1.0d, (java.lang.Number)10L, true);
   org.jfree.data.xy.XYDataItem xYDataItem8 = xYSeries2.getDataItem(0);
   java.lang.Number number9 = xYDataItem8.getX();
   java.lang.Number number10 = xYDataItem8.getX();
   java.lang.Number number11 = xYDataItem8.getX();
   xYDataItem8.setY(Double.NaN);
   java.lang.Number number14 = xYDataItem8.getY();

   // Regression assertion (captures the current behavior of the code)
   org.junit.Assert.assertNotNull(xYDataItem8);

   // Regression assertion (captures the current behavior of the code)
   org.junit.Assert.assertTrue("'" + number9 + "' != '" + 1.0d+ "'", number9.equals(1.0d));

   // Regression assertion (captures the current behavior of the code)
   org.junit.Assert.assertTrue("'" + number10 + "' != '" + 1.0d+ "'", number10.equals(1.0d));

   // Regression assertion (captures the current behavior of the code)
   org.junit.Assert.assertTrue("'" + number11 + "' != '" + 1.0d+ "'", number11.equals(1.0d));

   // Regression assertion (captures the current behavior of the code)
   org.junit.Assert.assertEquals(number14, Double.NaN, 0);

 }

As variable "number14" is an instance of type java.lang.Number, the compilation of the last statement fails. This is the compilation error:

error: no suitable method found for assertEquals(Number,double,int)
   org.junit.Assert.assertEquals(number14, Double.NaN, 0);
                   ^
   method Assert.assertEquals(String,Object,Object) is not applicable
     (argument mismatch; Number cannot be converted to String)
   method Assert.assertEquals(String,long,long) is not applicable
     (argument mismatch; Number cannot be converted to String)
   method Assert.assertEquals(String,double,double) is not applicable
     (argument mismatch; Number cannot be converted to String)
   method Assert.assertEquals(double,double,double) is not applicable
     (argument mismatch; Number cannot be converted to double)
   method Assert.assertEquals(float,float,float) is not applicable
     (argument mismatch; Number cannot be converted to float)
   method Assert.assertEquals(String,Object[],Object[]) is not applicable
     (argument mismatch; Number cannot be converted to String)

**Comment by bjkeller** [comment] 2016-01-19 17:51
Thank you for the report.

**Comment by mernst** [comment] 2016-01-19 18:30
Thanks for the bug report, Juan Pablo.  We appreciate it!

If you are able to give us a reproducible test case, that will help us to both investigate the problem and verify that the fix works for you.  For example, can you give the exact command line that you used to invoke Randoop, that would be great.  (It looks like you are running it on JFreeChart?)

**Comment by jgaleotti** [comment] 2016-01-19 18:45
Thanks Mike :)
Indeed, it is JFreeChart. Let me give you the command line we used:

java -cp /Users/galeotti/workspace-sbstcomp/jfreechart-1.0.19/target/classes:/Users/galeotti/randoop/dist/randoop.jar randoop.main.Main gentests --testclass=org.jfree.data.xy.XYSeries --timelimit=60 --junit-output-dir=/Users/galeotti/temp/testcases --junit-package-name=org.jfree.data.xy --classlist=/Users/galeotti/defects4j/framework/projects/Chart/loaded_classes/5.src --clear=10000 --string-maxlen=5000 --forbid-null=false --null-ratio=0.1 --no-error-revealing-tests=true --omitmethods=random

**Comment by bjkeller** [comment] 2016-01-21 00:28
Juan Pablo, I apologize for the delay.  The current head of the master branch has a fix for your issue.  You can clone the repository and run

    make distribution-files

which will build a new randoop.jar file for you.  This change will be included in the new version that we will release later this week.

I notice that you are using the --junit-package-name option. When this argument is used, the current head version will use package access to determine what to include in the test. If you want to restrict the test to public members, also use the option --only-test-public-members. 

Thanks for reporting the bug. If you run into other issues, please let us know.
Ben

**Closed by bjkeller** 2016-01-21 00:28 UTC
