### ISSUE TITLE
Support for other java versions

### ISSUE THREAD

**Issue by mihairaulea** [randoop/randoop#298] opened 2018-01-04 08:01 UTC
Hello,
I really love your product, i think you are one of the best solutions for automated test generation.
I was wondering why the generated tests have a hard requirement for compatibility with java 8, and nothing else, and if there is any way around this.
Thank you.

**Comment by mernst** [comment] 2018-01-04 19:42
I don't believe that the generated tests require Java 8, nor does Randoop require Java 8.
Note that the Randoop tests succeed under both Java 7 and Java 8:  https://travis-ci.org/mernst/randoop/builds/324604957 .

Can you give a reproducible test case that shows a dependence on Java 8?

**Comment by mernst** [comment] 2018-02-21 18:43
I'm closing this because Randoop handles Java 7 and up.

**Closed by mernst** 2018-02-21 18:43 UTC
