### ISSUE TITLE
Randoop failed in an unexpected way

### ISSUE THREAD

**Issue by alvawei** [randoop/randoop#342] opened 2018-04-14 05:39 UTC
cd /tmp
git clone https://github.com/apache/commons-collections
(place hamcrest-core-1.3.jar, junit-4.12.jar, randoop-4.0.3 directory in the same directory)
java -classpath junit-4.12.jar:hamcrest-core-1.3.jar:commons-collections/target/classes:randoop-4.0.3/randoop-all-4.0.3.jar randoop.main.Main gentests --testclass=org.apache.commons.collections4.map.Flat3Map --time-limit=60

Randoop fails after generating RegressionTest0.java. Encountered when doing Assignment 3 for CSE 403. Error message:

Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues .
randoop.BugInRandoopException: Check configuration of test environment: initialization error of test in flaky-test filter: 1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
	at randoop.output.FailingTestFilter.commentFailingAssertions(FailingTestFilter.java:262)
	at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:121)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:600)
	at randoop.main.GenTests.handle(GenTests.java:511)
	at randoop.main.Main.nonStaticMain(Main.java:65)
	at randoop.main.Main.main(Main.java:29)

**Comment by mernst** [comment] 2018-04-14 05:42
This looks similar to #341.  See the discussion there.  Could you try on CentOS?

**Comment by mernst** [comment] 2018-05-04 16:01
I'm closing this because the original poster has not responded to the request for more information.

**Closed by mernst** 2018-05-04 16:01 UTC
Labels: unreproducible

**Comment by marciomribeiro** [comment] 2018-08-18 20:44
Dear mernst,

I am facing the exact same problem... what is interesting, nevertheless, is that Randoop still creates a RegressionTest0.java file with 188 test cases.

Here is my environment with some screenshots. I hope it helps!

================================
Java / Operating System / Eclipse / Randoop
================================

Java SE 8 [1.8.0_171]
macOS High Sierra 10.13.4
Eclipse IDE for Java Developers - Version: Neon.3 Release (4.6.3)
lib/randoop-all-4.0.1.jar

========
Arguments
========

Main class: randoop.main.Main
gentests --classlist=src/classesToTest.txt --time-limit=5
classesToTest.txt ==> br.ufal.ic.testingtools.stack.Stack

=================
Eclipse console output:
=================

PUBLIC MEMBERS=8
Explorer = randoop.generation.ForwardGenerator(allSequences.size()=0,observers.size()=0,subsumed_sequences.size()=0,runtimePrimitivesSeen.size()=38)

Progress update: steps=0, test inputs generated=0, failing inputs=0      (Sat Aug 18 17:27:20 BRT 2018)
Progress update: steps=324, test inputs generated=262, failing inputs=0      (Sat Aug 18 17:27:25 BRT 2018)
Normal method executions: 2336
Exceptional method executions: 62

Average method execution time (normal termination):      0.00787
Average method execution time (exceptional termination): 0.0438

No error-revealing tests to output

Regression test output:
Regression test count: 150
Writing JUnit tests...

Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues .
randoop.BugInRandoopException: Check configuration of test environment: initialization error of test in flaky-test filter: 1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
	at randoop.output.FailingTestFilter.commentFailingAssertions(FailingTestFilter.java:262)
	at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:121)
	at randoop.main.GenTests.writeTestFiles(GenTests.java:600)
	at randoop.main.GenTests.handle(GenTests.java:511)
	at randoop.main.Main.nonStaticMain(Main.java:65)
	at randoop.main.Main.main(Main.java:29)

========================
Screenshots of my environment:
========================

<img width="1552" alt="screen shot 2018-08-18 at 17 28 09" src="https://user-images.githubusercontent.com/2229847/44303032-a51ee300-a30c-11e8-873c-b1daea566350.png">

<img width="1524" alt="screen shot 2018-08-18 at 17 31 14" src="https://user-images.githubusercontent.com/2229847/44303033-acde8780-a30c-11e8-9599-7ef1e014d24f.png">

<img width="1524" alt="screen shot 2018-08-18 at 17 31 22" src="https://user-images.githubusercontent.com/2229847/44303034-b36cff00-a30c-11e8-8e6b-77d7c46ce5a6.png">
