### ISSUE TITLE
No test

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [randoop/randoop#967] opened 2021-08-31 02:00 UTC
Thank you for the great work and support on Randoop.

I used Randoop for several programs, and it works well. However, it cannot generate tests for the attached program. Almost all methods have public visibility, and I do not make any striction to ignore any method. I also tried recommended suggestions on the page, but it did not help. I would appreciate it if you can help me with this case.

I used the following command:

java -ea -classpath /home/amirfarhad/Desktop/ProgramAnalysis/codes/Randoop/StudentEnrollment/bin:/home/amirfarhad/Desktop/ProgramAnalysis/Tools/randoop-4.2.6/randoop-all-4.2.6.jar randoop.main.Main gentests --testclass=org.StudentEnrollment

[StudentEnrollment.zip](https://github.com/randoop/randoop/files/7080477/StudentEnrollment.zip)

Thanks in advance for your time and consideration.

**Comment by umarmahmud** [comment] 2021-12-09 03:31
This bug is not reproducible. Please consider closing the issue.

**Comment by mernst** [comment] 2022-02-05 19:40
I'm sorry you were having trouble.
I can reproduce this problem.

The problem is the visibility of methods.  You say:

> Almost all methods have public visibility,

However, the constructor for `StudentEnrollment` does *not* have public visibility!  Therefore, Randoop cannot call it, cannot create any objects of type `StudentEnrollment`, and cannot call any member methods.

There are two ways to fix the problem:
 * give the constructor for `StudentEnrollment` public visibility
 * generate tests in the `org` package, from which the constructor is visible.  Use the command-line argument `--junit-package-name=org`

**Closed by mernst** 2022-02-05 19:40 UTC
