### ISSUE TITLE
Regression assertion comparison issue for Float.NaN, Double.NaN... using == 

### ISSUE THREAD

**Issue by terminiter** [randoop/randoop#61] opened 2015-11-13 18:08 UTC
// Regression assertion (captures the current behavior of the code) assertTrue(var6 == Double.NaN);
This is incorrect, because using == on two NaN values always returns false. A corrected version of the above assertion should be:
// Regression assertion (captures the current behavior of the code) assertEquals(var6, Double.valueOf(Double.NaN));

Code example that reveals the issue that produced by Randoop.
double var1 = org.apache.commons.math3.util.FastMath.log((double)(-5.801203960010585d));
    // Regression assertion (captures the current behavior of the code)
    assertTrue(var1 == Double.NaN);// This always return false!

**Comment by mernst** [comment] 2015-11-13 18:15
I'm sorry you are having trouble.

This appears to be a duplicate of issue #13, which was fixed by commit e09c55d3f9dd39896836fb813e4b772b38063103 on May 31, 2015.

If you are still encountering the problem, then can you please submit a complete, reproducible bug report?  Given just a snippet of Randoop's output, I cannot tell what you did to produce the Randoop output, so I cannot reproduce the problem nor verify a fix.  Instructions for submitting a bug report appear at https://rawgit.com/randoop/randoop/master/doc/index.html#getting_help

**Closed by mernst** 2015-11-13 18:15 UTC

**Comment by terminiter** [comment] 2015-11-13 18:17
Thanks for fixing the issue, I will check it again later and come back if problems exist.
