### ISSUE TITLE
Compilation error during flaky-test filtering

### ISSUE THREAD

**Issue by Ahmedfir** [randoop/randoop#597] opened 2019-09-18 09:18 UTC
I am trying to generate a mockito test suite with randoop. randoop failed to write regression test files because of an uncompilable sequence, caused by a bad use of the java.lang.Short class.

here's the stack trace:

Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues ,
providing the information requested at https://randoop.github.io/randoop/manual/index.html#bug-reporting .
randoop.main.RandoopBug: Compilation error during flaky-test filtering: fileCompiler.compile(sourceFile, /var/folders/t_/xgyhs9l554921n9r4cpxd8rs9bnzt3/T/checkRegressionTest103851035410284107241)
Use --print-non-compiling-file to print the file with the compilation error.
Diagnostics:
[/Users/ahmed.khanfir/IdeaProjects/mockito/src/test/java/randoop/mockito/RegressionTest1.java:3413: error: type java.lang.Short does not take parameters
        java.lang.Short<org.mockito.internal.util.Primitives> primitivesShort0 = new java.lang.Short<org.mockito.internal.util.Primitives>();
                       ^, /Users/ahmed.khanfir/IdeaProjects/mockito/src/test/java/randoop/mockito/RegressionTest1.java:3413: error: type java.lang.Short does not take parameters
        java.lang.Short<org.mockito.internal.util.Primitives> primitivesShort0 = new java.lang.Short<org.mockito.internal.util.Primitives>();
                                                                                                    ^, Note: /Users/ahmed.khanfir/IdeaProjects/mockito/src/test/java/randoop/mockito/RegressionTest1.java uses or overrides a deprecated API., Note: Recompile with -Xlint:deprecation for details.]

        at randoop.output.FailingAssertionCommentWriter.compilationError(FailingAssertionCommentWriter.java:262)
        at randoop.output.FailingAssertionCommentWriter.commentCatchStatements(FailingAssertionCommentWriter.java:225)
        at randoop.output.FailingAssertionCommentWriter.writeClassCode(FailingAssertionCommentWriter.java:135)
        at randoop.main.GenTests.writeTestFiles(GenTests.java:837)
        at randoop.main.GenTests.handle(GenTests.java:535)
        at randoop.main.Main.nonStaticMain(Main.java:66)
        at randoop.main.Main.main(Main.java:30)
Caused by: randoop.compile.FileCompiler$FileCompilerException: Compilation failed
        at randoop.compile.FileCompiler.compile(FileCompiler.java:64)
        at randoop.compile.FileCompiler.compile(FileCompiler.java:77)
        at randoop.output.FailingAssertionCommentWriter.compileTestClass(FailingAssertionCommentWriter.java:534)
        at randoop.output.FailingAssertionCommentWriter.writeClassCode(FailingAssertionCommentWriter.java:132)
        ... 4 more
 
I am using the same environment and running command as in https://github.com/randoop/randoop/issues/595

**Comment by mernst** [comment] 2020-01-17 16:11
> I am using the same environment and running command as in #595

Unfortunately, issue #595 is not reproducible.  That bug report is missing a dozen files that are needed by the command.  Could you please provide a simpler test case (if possible), but either way, please provide a complete, reproducible command?  Thanks!

**Comment by mernst** [comment] 2020-02-03 06:43
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2020-02-03 06:43 UTC
Labels: unreproducible

**Comment by Ahmedfir** [comment] 2020-02-03 10:10
same as #595 .
