### ISSUE TITLE
Generated tests using replace call agent not using replaced methods/classas

### ISSUE THREAD

**Issue by vipulchadda** [randoop/randoop#530] opened 2019-07-05 10:18 UTC
**The version of Randoop, the output of `java -version`, and the operating system version.**
Randoop version: 4.1.2
Java version: "1.8.0_60"
OS: Windows 10

**The commands you ran, so that we can paste them into a command terminal.  Please don't omit any steps, including installing software or setting environment varibales.**
java -ea -Xmx3000m -classpath randoop-all-4.1.2.jar;avenger-0.0.1-SNAPSHOT.jar -Xbootclasspath/a:C:\Projects\avenger\temp\replacecall-4.1.2.jar  -javaagent:C:\Projects\avenger\temp\replacecall-4.1.2.jar=--replacement-file=replacements.txt randoop.main.Main gentests --classlist=classlist.txt --output-limit=100

**A transcript of all the output (as text, not a screenshot).**
PUBLIC MEMBERS=51
Explorer = randoop.generation.ForwardGenerator(allSequences.size()=0,observers.size()=0,subsumed_sequences.size()=0,runtimePrimitivesSeen.size()=38)

Progress update: steps=1, test inputs generated=0, failing inputs=0      (Fri Jul 05 12:18:50 IST 2019)
Progress update: steps=184, test inputs generated=101, failing inputs=2      (Fri Jul 05 12:18:58 IST 2019)
Normal method executions: 1277
Exceptional method executions: 7

Average method execution time (normal termination):      0.498
Average method execution time (exceptional termination): 17.6

Error-revealing test output:
Error-revealing test count: 2
Writing JUnit tests...

Created file C:\Projects\avenger\temp\ErrorTest0.java
Created file C:\Projects\avenger\temp\ErrorTestDriver.java

Regression test output:
Regression test count: 47
Writing JUnit tests...

Created file C:\Projects\avenger\temp\RegressionTest0.java
Created file C:\Projects\avenger\temp\RegressionTestDriver.java

Invalid tests generated: 0

**What you expected to happen instead.**
We are trying to generate tests for a delegate class that uses a service and need to mock the service. The delegate uses getService() method to get the service instance and that method is mocked in the replacement. When running the generated tests, the mock is never used and the tests are failing. Even the replacements for java.awt.Component included in the default-replacements.txt is not replaced. The following code actually shows the  frame while executing the tests:
`Component f = new Frame();
f.setVisible(true);`

**Files that are used by the commands you ran.**
classlist.txt: 
com.avenger.AvengerDelegate

replacements.txt: 
com.avenger.AvengerDelegate.getAvengerService() com.avenger.mock.AvengerDelegateMock.getAvengerService(com.avenger.AvengerDelegate)

**Comment by mernst** [comment] 2019-07-06 01:52
I'm sorry you are having trouble.  Thanks for getting in touch.
Could you please provide all the files used by your commands?  I can't reproduce your problem, because the file `avenger-0.0.1-SNAPSHOT.jar` is missing.

**Comment by vipulchadda** [comment] 2019-07-08 05:19
Sorry about that. Attaching the jar file here.

[avenger-0.0.1-SNAPSHOT.jar.zip](https://github.com/randoop/randoop/files/3366763/avenger-0.0.1-SNAPSHOT.jar.zip)

**Comment by markro49** [comment] 2019-07-09 17:48
It looks like your file organization does not agree with replacement.txt.  replacement.txt refers to com.veer.avenger but that directory is empty and the expected files appear to be in com.avenger.

**Comment by vipulchadda** [comment] 2019-07-11 09:17
Sorry about that, the classes were rearranged and the replacement.txt file in the resources was not used. The replacement.txt provided in the description above is the correct one.

**Comment by markro49** [comment] 2019-07-15 14:35
I'm sorry, but I don't understand your comment.  If the problem still exists, please resubmit the jar file with the corrections to reproduce the problem.  Thank you.

**Comment by mernst** [comment] 2019-07-20 12:05
@vipulchadda Ping.

**Comment by mernst** [comment] 2020-01-13 17:53
I'm closing this because the reporter never provided a reproducible test.  If someone can provide a reproducible test, we can re-open the issue.

**Closed by mernst** 2020-01-13 17:53 UTC
