### ISSUE TITLE
randoop makes no progress and produces no output

### ISSUE THREAD

**Issue by markro49** [randoop/randoop#365] opened 2018-05-22 15:07 UTC
1) set up the randoop pascali coverage suite => https://gitlab.cs.washington.edu/randoop/pascali-coverage
2) cd to the directory established in step (1)
3) cd integration-test2
4) run './run_randoop.py facer'
5) the various output files will be in integration-test2/corpus/facer/dljc-out
6) i have attached randoop.log from that directory
[randoop.log](https://github.com/randoop/randoop/files/2027263/randoop.log)

**Comment by mernst** [comment] 2018-06-10 21:47
I cannot reproduce this problem.  Instead, I get a different problem:

```
Unexpected exception java.lang.ThreadDeath (null) in CallReplacementTransformer.transform(java/awt/EventQueue)
java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:853)
	at randoop.util.ReflectionExecutor.executeReflectionCodeThreaded(ReflectionExecutor.java:146)
	at randoop.util.ReflectionExecutor.executeReflectionCode(ReflectionExecutor.java:90)
	at randoop.operation.MethodCall.execute(MethodCall.java:180)
	at randoop.operation.TypedOperation.execute(TypedOperation.java:258)
	at randoop.sequence.Statement.execute(Statement.java:163)
	at randoop.sequence.ExecutableSequence.executeStatement(ExecutableSequence.java:403)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:300)
	at randoop.sequence.ExecutableSequence.execute(ExecutableSequence.java:228)
	at randoop.generation.ForwardGenerator.step(ForwardGenerator.java:152)
	at randoop.generation.AbstractGenerator.createAndClassifySequences(AbstractGenerator.java:302)
	at randoop.main.GenTests.handle(GenTests.java:452)
	at randoop.main.Main.nonStaticMain(Main.java:67)
	at randoop.main.Main.main(Main.java:31)
```

Could you try again using the latest version of Randoop?

**Comment by markro49** [comment] 2018-06-11 22:26
I get the same as above with e00eebd9a1a41b41791a7a6f040ce41a2a6ddb15.

**Comment by markro49** [comment] 2018-06-11 22:32
To be clear - I got the same as the new log you listed above.

**Comment by mernst** [comment] 2018-06-11 23:34
After committing 52d72b5 I get the original behavior (no tests generated).
I agree this is bad behavior, but it's not necessarily a bug in Randoop.
To investigate this, one should follow these instructions in the Randoop Manual: https://randoop.github.io/randoop/manual/index.html#not-enough-tests-created
I'm going to close this unless there is a specific Randoop bug report or specific feature request.

**Closed by mernst** 2018-06-11 23:34 UTC
