### ISSUE TITLE
Can Tests Be Generated If Constructors Fail?

### ISSUE THREAD

**Issue by opticyclic** [randoop/randoop#134] opened 2016-12-15 03:20 UTC
I was hoping to get Randoop to generate tests for these methods
https://github.com/zhuowei/RaspberryJuice/blob/master/src/main/java/net/zhuoweizhang/raspberryjuice/RemoteSession.java#L486-L512

I started Randoop like this

    java -ea -classpath Minecraft_Server.jar:plugins/raspberryjuice-1.8.jar:../Randoop/randoop-all-3.0.8.jar randoop.main.Main gentests --classlist=myclasses.txt --methodlist=methods.txt --timelimit=180

myclasses.txt contains: `net.zhuoweizhang.raspberryjuice.RemoteSession`

And methods.txt contains `method : net.zhuoweizhang.raspberryjuice.RemoteSession.parseRelativeBlockLocation(java.lang.String, java.lang.String, java.lang.String)`

However, the only tests that are generated are for the static method `blockFaceToNotch` and the constructor.

Why is the method I specified not being tested?

Could it be because the constructor is throwing a null pointer exception?

**Comment by bjkeller** [comment] 2016-12-15 04:35
If there is no object to receive the method, then the method won't be called. Does the constructor throw an exception during execution?

**Comment by mernst** [comment] 2018-02-21 19:14
I'm closing this issue because the original submitter didn't answer questions or provide a reproducible test case.  We can re-open it if we get more information.

**Closed by mernst** 2018-02-21 19:14 UTC

**Comment by opticyclic** [comment] 2018-02-21 20:29
Sorry about that.
The original issue does answer the question though by stating that a NPE is thrown and you could clone the project listed to test it.
If I get round to creating an isolated test to demonstrate it I'll open a new issue.

**Comment by mernst** [comment] 2018-02-21 20:35
You are right.  (Sorry about that!)

I should have said that there wasn't an answer to Ben's question about throwing the exception.  (And with no answer, I assumed that you weren't interested or couldn't reproduce the problem.)  Is this still an issue for you?  If so, I will re-open it (or you can).

Thanks.
