### ISSUE TITLE
BugInRandoopException  unexpected way

### ISSUE THREAD

**Issue by anuprk** [randoop/randoop#423] opened 2019-01-19 03:30 UTC
Got following error while generating test cases on macOS mojave with jdk11.

Command - gentest --classlist=classlist.txt 

Progress update: steps=6152, test inputs generated=2619, failing inputs=10      (Fri Jan 18 19:15:37 PST 2019)
Normal method executions: 367226
Exceptional method executions: 424

Average method execution time (normal termination):      0.192
Average method execution time (exceptional termination): 0.0651

Error-revealing test output:
Error-revealing test count: 10
Writing JUnit tests...

Created file /Users/anup/Workstation/svn_views/integral-modules-1.8/serializer/src/test/java/com/integral/serializer/regression/ErrorTest0.java
Created file /Users/anup/Workstation/svn_views/integral-modules-1.8/serializer/src/test/java/com/integral/serializer/regression/ErrorTest.java

Regression test output:
Regression test count: 1340
Writing JUnit tests...

Randoop failed in an unexpected way.
Please report at https://github.com/randoop/randoop/issues .
randoop.BugInRandoopException: Did not find "There\s+(?:was|were)\s+(\d+)\s+failure(?:s|):" in execution of com.integral.serializer.regression.RegressionTest0
status=Status for command "java -ea -classpath .:/Users/anup/Workstation/svn_views/integral-modules-1.8/serializer/build/classes/java/test:/Users/anup/Workstation/svn_views/integral-modules-1.8/serializer/build/resources/test:/Users/anup/Workstation/svn_views/integral-modules-1.8/serializer/build/classes/java/main:/Users/anup/Workstation/svn_views/integral-modules-1.8/serializer/build/resources/main:/Users/anup/.gradle/caches/modules-2/files-2.1/com.integral/log/1.0.2/c833bf9d70125463ea5c288d293077d5cf46627b/log-1.0.2.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/org.codehaus.jackson/jackson-core-asl/1.9.13/3c304d70f42f832e0a86d45bd437f692129299a4/jackson-core-asl-1.9.13.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.4.3/4cb3dbb0c2f75b51aa7543c53252989785a0c609/jackson-core-2.4.3.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.4.3/feff63199be7b8f495c2f3e2096dcb6bd5e5b0b3/jackson-databind-2.4.3.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.4.3/a30ec6f59b6d31b2df06fa73925fda2fc7e84486/jackson-annotations-2.4.3.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-artifact/3.0.3/cb2a26ac02d1e6275712c331fce0ddeeb57d3f9e/maven-artifact-3.0.3.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.13.0-GA/a20c763a4edec3a62021ac99b151bb0c75a75f03/javassist-3.13.0-GA.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/de.undercouch/bson4jackson/2.4.0/6515cf6211f044965854e9c92db5a89fb9339534/bson4jackson-2.4.0.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/org.jmockit/jmockit/1.9/16019ef656297861e2a2aa1ba6a8bc43a5b12738/jmockit-1.9.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/junit/junit/4.11/4e031bb61df09069aeb2bffb4019e7a5034a4ee0/junit-4.11.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/ch.qos.logback/slf4j-api/1.6.1/37ec7b9f4640c525a3b00b6fcac9ccc99f361ed3/slf4j-api-1.6.1.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/com.googlecode.disruptor/disruptor/2.8/dd22989e040b12628eeee369a21e6604612c5072/disruptor-2.8.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.0.6/495230759c86bf018831360f6572e2ff4db4eb81/logback-classic-1.0.6.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/com.integral/util/1.0/233915fa343f0e9b03ad001c5e726bc7d39a8ac4/util-1.0.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.0.6/411891feba2f0b8e7a9d65816c5f1eb41f23efdc/logback-core-1.0.6.jar:/Users/anup/.gradle/caches/modules-2/files-2.1/org.jctools/jctools-core/1.1/e1b19da712c9f361fe5e5ab3f196c988c42b77c4/jctools-core-1.1.jar:/Users/anup/randoop/randoop-all-4.1.0.jar org.junit.runner.JUnitCore com.integral.serializer.regression.RegressionTest0" = 1 (timedOut=false), stdout="JUnit version 4.11"
, stderr lines=22
Standard output:
JUnit version 4.11
... end of standard output.

        at randoop.output.FailingTestFilter.numJunitFailures(FailingTestFilter.java:379)
        at randoop.output.FailingTestFilter.commentFailingAssertions(FailingTestFilter.java:245)
        at randoop.output.FailingTestFilter.writeClassCode(FailingTestFilter.java:120)
        at randoop.main.GenTests.writeTestFiles(GenTests.java:600)
        at randoop.main.GenTests.handle(GenTests.java:511)
        at randoop.main.Main.nonStaticMain(Main.java:67)
        at randoop.main.Main.main(Main.java:31)

**Comment by mernst** [comment] 2019-01-19 04:48
I'm sorry you are having trouble.

Could you please provide a reproducible test case?  The manual, and also the instructions that you deleted in order to submit this bug report, told you how.  For example, you need to provide the code under test, the classlist.txt file, the exact command line you ran, etc.

Thanks!

**Comment by mernst** [comment] 2019-01-28 17:58
Since the original poster has not submitted a reproducible test case, I am closing this issue.
We can re-open it if someone shows how to reproduce the problem.

**Closed by mernst** 2019-01-28 17:58 UTC
Labels: unreproducible
